name: 'torii-ila CI'
on: [ push, pull_request ]

env:
  TOOL_PYTHON_VERSION: '3.11'

jobs:
  lint-torii-ila:
    runs-on: ubuntu-latest
    name: 'Lint torii-ila'
    steps:
      - name: 'Setup Python (${{ env.TOOL_PYTHON_VERSION }})'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TOOL_PYTHON_VERSION }}

      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Install Dependencies'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Run Style Lint'
        shell: bash
        continue-on-error: true
        run: |
          nox -s lint

      - name: 'Run Type Checking'
        shell: bash
        continue-on-error: true
        run: |
          nox -s typecheck

  test-torii-ila:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13', ]
        allow-failure:
         - false
        include:
          - python-version: '3.14-dev'
            allow-failure: true

    name: 'Test torii-ila (Python ${{ matrix.python-version }})'
    continue-on-error: ${{ matrix.allow-failure }}
    steps:
      - name: 'Setup Python (${{ matrix.python-version }})'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Install Dependencies'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Setup OSS CAD Suite'
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Run Tests'
        shell: bash
        run: |
          nox -s test

      - name: 'Codecov Upload'
        if: success() && github.repository == 'shrine-maiden-heavy-industries/torii-ila'
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/tests/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  linkcheck-docs:
    runs-on: ubuntu-latest
    name: 'torii-ila Docs - Link-check'
    steps:
      - name: 'Setup Python (${{ env.TOOL_PYTHON_VERSION }})'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TOOL_PYTHON_VERSION }}

      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Install Dependencies'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Link Check'
        shell: bash
        run: |
          nox -s docs_linkcheck


  build-docs:
    runs-on: ubuntu-latest
    name: 'torii-ila Docs - Build'
    steps:
      - name: 'Setup Python (${{ env.TOOL_PYTHON_VERSION }})'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TOOL_PYTHON_VERSION }}

      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Install Dependencies'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Build Docs'
        shell: bash
        run: |
          nox -s docs

      - name: 'Upload docs artifact'
        if: success() && github.repository == 'shrine-maiden-heavy-industries/torii-ila' && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/tags/v')) && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./build/docs
          retention-days: 1

  docs:
    name: 'torii-ila Docs (Meta Job)'
    needs:
      - linkcheck-docs
      - build-docs
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}

  ci-checkpoint:
    name: 'torii-ila CI Checkpoint (Meta Job)'
    needs:
      - lint-torii-ila
      - test-torii-ila
      - docs
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}

  publish-docs:
    name: 'Publish torii-ila Docs'
    if: github.repository == 'shrine-maiden-heavy-industries/torii-ila' && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/tags/v')) && github.event_name == 'push'
    needs:
      - ci-checkpoint
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Download docs artifact'
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: built_docs/

      - name: 'Deploy Docs'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: built_docs/
          clean: true

  publish-pypi:
    name: 'torii-ila - Publish PyPi package'
    if: github.repository == 'shrine-maiden-heavy-industries/torii-ila' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') && !contains(github.event.ref, 'dev')
    needs:
      - publish-docs
      - ci-checkpoint
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/torii-ila
    permissions:
      id-token: write
    steps:
      - name: 'Setup Python (${{ env.TOOL_PYTHON_VERSION }})'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TOOL_PYTHON_VERSION }}

      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Install Dependencies'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox twine build

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Build wheel'
        shell: bash
        run: |
          nox -s dist

      - name: 'Check package'
        shell: bash
        run: |
          twine check build/dist/*

      - name: 'Publish to PyPi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: build/dist/

      - name: 'Upload wheel artifact'
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: build/dist/
