name: 'Torii ILA PR Tests'
on:
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Lint Torii ILA'
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Initialize Env'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Run Style Check'
        shell: bash
        continue-on-error: true
        run: |
          nox -s lint

  test-torii-ila:
    name: 'Torii ILA PR Tests (Python ${{ matrix.python-version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14.0-alpha.2']
      fail-fast: true

    steps:
      - name: 'Setup Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Initialize Env'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup OSS CAD Suite'
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Setup'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Run Tests'
        shell: bash
        timeout-minutes: 15 # Python 3.12, 3.13, and 3.14 seem to just hang on testing ~sometimes~
        continue-on-error: ${{ matrix.python-version == '3.12' || matrix.python-version == '3.13' || matrix.python-version == '3.14.0-alpha.2' }}
        run: |
          nox -s test

      - name: 'Codecov Upload'
        uses: codecov/codecov-action@v4
        if: success() && github.repository == 'shrine-maiden-heavy-industries/torii-ila'
        continue-on-error: true # It's not super mission critical that the coverage upload fails
        with:
          verbose: true
          files: ./build/tests/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
